// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_dallinb9.Models;

namespace Mission06_dallinb9.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230214060528_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_dallinb9.Models.NewMovieModel", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Sci-fi",
                            Director = "Christopher Nolan",
                            Edited = "",
                            LentTo = "",
                            Notes = "My favorite movie ever",
                            Rating = "PG-13",
                            Title = "Interstellar",
                            Year = 2014
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Sci-fi",
                            Director = "Doug Liman",
                            Edited = "",
                            LentTo = "",
                            Notes = "My fav Tom Cruise movie",
                            Rating = "PG-13",
                            Title = "Edge of Tomorrow",
                            Year = 2014
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Action",
                            Director = "William Phelps",
                            Edited = "",
                            LentTo = "",
                            Notes = "All-time family favorite",
                            Rating = "PG",
                            Title = "North Shore",
                            Year = 1987
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
